default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  port: 5600
  host: localhost
  timeout: 5000
  variables:
    citus.shard_count: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres
  username: postgres
  password: postgres
  host: localhost
